config/routes.rb
Rails.application.routes.draw do
  resources :courses
  resources :students
  root to: 'courses#index'

end

app/models/classroom.rb
class Classroom < ActiveRecord::Base

   belongs_to :course
   belongs_to :student
end

app/models/course.rb
class Course < ActiveRecord::Base


   has_many :classrooms
   has_many :students, :through => :classrooms
end

app/models/student.rb
class Student < ActiveRecord::Base

   validates :name, :presence => true

   belongs_to :classrooms
   #belongs_to :courses, :through => :classrooms
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
        @studentsclass = Classroom.where(:course_id => params[:id])
        @students ||= []
        @studentsclass.each do |lala|
          @students << Student.where(:id => lala.student_id)
        end
  end

  # GET /courses/new
  def new
    @course = Course.new
    @all_students = Student.all
    @classrooms = @course.classrooms.build

  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)
    @student = params[:students][:student_id]


     @student.each do |student|
      if !student.empty?

        @course.classrooms.build(:student_id => student)
      end
    end
    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def enrol
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:name, :description, :status)
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:name, :register_number, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/courses/_form.html.slim
= form_for @course do |f|
  - if @course.errors.any?
    #error_explanation
      h2 = "#{pluralize(@course.errors.count, "error")} prohibited this course from being saved:"
      ul
        - @course.errors.full_messages.each do |message|
          li = message

  .ls-label.col-md-3
    .ls-label-text Nome Curso
    = f.text_field :name
  .ls-label.col-md-3
    .ls-label-text Descricao
    = f.text_field :description
  .ls-label.col-md-3
    .ls-label-text Status
    = f.number_field :status
    .ls-label.col-md-3
    = fields_for (@classrooms) do |cl|
        = collection_select(:students, :student_id, @all_students, :id, :name, {}, {:multiple => true})
  .ls-btn = f.submit

app/views/courses/edit.html.slim
h1.ls-title.intro Modificar Curso

== render 'form'

.ls-btn = link_to 'Mostrar', @course
.ls-btn.atl-btn = link_to 'Voltar', courses_path

app/views/courses/index.html.slim
h1.ls-title-intro Cursos

table.ls-table
  thead
    tr
      th Curso
      th Descricao
      th Status
      th
      th
      th

  tbody
    - @courses.each do |course|
      tr
        td = course.name
        td = course.description
        td = course.status
        td = link_to 'Mostrar', course
        td = link_to 'Modificar', edit_course_path(course)
        td = link_to 'Deletar', course, data: {:confirm => 'Tem certeza?'}, :method => :delete

br

.ls-btn = link_to 'Adicionar Curso', new_course_path

app/views/courses/new.html.slim
h1.ls-title-intro Adicionar Curso

== render 'form'

ls.btn= link_to 'Voltar', courses_path

app/views/courses/show.html.slim
h1.ls-title.intro = @course.name

p#notice = notice

p
  strong Curso:
  = @course.name

p
  strong Descricao:
  = @course.description
p
  strong Status:
  = @course.status

  table
  thead
    tr
      th Name

  tbody
    - @students.each do |student|
      tr
        td = student.name
.ls-btn = link_to 'Modificar', edit_course_path(@course)
.ls-btn.alt-btn= link_to 'Voltar', courses_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html  class="ls-theme-light-blue">
<head>
  <title>Matricula</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">

</head>

<div class="ls-topbar ">

  <!-- Barra de Notificações -->
  <div class="ls-notification-topbar">
    <!-- Dropdown com detalhes da conta de usuário -->
    <div class="ls-user-account">
      <a class="ls-ico-user">
        <span class="">Acesso:Diego</span>
      </a>
    </div>
  </div>

  <span class="ls-show-sidebar ls-ico-menu"></span>


  <!-- Nome do produto/marca com sidebar -->
    <h1 class="ls-brand-name">
      <a  class="fa fa-power-off">
      <div style="margin-left: 40px;">
        <small>Matricula</small>
        </div>
      </a>
    </h1>

  <!-- Nome do produto/marca sem sidebar quando for o pre-painel  -->
</div>


    <aside class="ls-sidebar">

  <div class="ls-sidebar-inner">

      <nav class="ls-menu">
        <ul>
            <li><%= link_to "Cursos", courses_path, class: "ls-ico-home" %></li>
             <li><%= link_to "Estudantes", students_path,  class: "ls-ico-user" %></li>


  <!--            <li>
            <a href="#" class="ls-ico-cog" title="Configurações">Configurações</a>
            <ul>
              <li><a href="/locawebstyle/documentacao/exemplos/painel1/config-domain">Domínios da Revenda</a></li>
              <li><a href="/locawebstyle/documentacao/exemplos/painel1/config-email">E-mail de Remetente</a></li>
              <li><a href="/locawebstyle/documentacao/exemplos/painel1/config-aspect">Aparência</a></li>
              <li><a href="/locawebstyle/documentacao/exemplos/painel1/config-answer">Atendimento</a></li>
              <li><a href="/locawebstyle/documentacao/exemplos/painel1/config-api">Chave de acesso para API</a></li>
            </ul>
          </li> -->
        </ul>
      </nav>


  </div>
</aside>


    <main class="ls-main ">
      <div class="container-fluid">

        <%= yield %>

      </div>
    </main>
</body>
</html>

app/views/students/_form.html.slim
= form_for @student do |f|
  - if @student.errors.any?
    #error_explanation
      h2 = "#{pluralize(@student.errors.count, "error")} prohibited this student from being saved:"
      ul
        - @student.errors.full_messages.each do |message|
          li = message

  .ls-label.col-md-3
    .ls-label-text Nome Estudante
    = f.text_field :name
  .ls-label.col-md-3
    .ls-label-text RA
    = f.text_field :register_number
  .ls-label.col-md-3
    .ls-label-text Status
    = f.number_field :status
  .ls-btn = f.submit

app/views/students/edit.html.slim
h1.ls-title-intro Modificar Estudante

== render 'form'

.ls-btn = link_to 'Mostrar', @student
.ls-btn.alt-btn = link_to 'Voltar', students_path

app/views/students/index.html.slim
h1.ls-title-intro Estudantes

table.ls-table
  thead
    tr
      th Name
      th Register number
      th Status
      th
      th
      th

  tbody
    - @students.each do |student|
      tr
        td = student.name
        td = student.register_number
        td = student.status
        td = link_to 'Show', student
        td = link_to 'Edit', edit_student_path(student)
        td = link_to 'Destroy', student, data: {:confirm => 'Are you sure?'}, :method => :delete

br

.ls-btn = link_to 'Adicionar Estudante', new_student_path

app/views/students/new.html.slim
h1.ls-title-intro Adicionar Estudante

== render 'form'

.ls-btn = link_to 'Voltar', students_path

app/views/students/show.html.slim
h1.ls-title-intro = @student.name

p#notice = notice

p
  strong Nome:
  = @student.name
p
  strong RA:
  = @student.register_number
p
  strong Status:
  = @student.status

.ls-btn = link_to 'Edit', edit_student_path(@student)
.ls-btn.alt-btn = link_to 'Back', students_path